FROM python:3.10-slim

WORKDIR . /app

COPY requirements.txt .

RUN pip install --np-cache-dir requirements.txt

COPY . .

EXPOSE $PORT

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]